language: node_js
node_js:
  - 12

dist: trusty
sudo: false

addons:
  chrome: stable

install:
  - npm --version
  - npm i

script:
  - npm run lint
  - npm run test
  - npm run build

cache:
  directories:
    - node_modules